// Package coffer.v1 — the worker-facing read API for coffer.
//
// At trial scope the only RPC is GetCredentials. Transfer workers
// present a signed per-job capability token (ed25519, see ADR 0002)
// and a bounded list of credential IDs; the vault verifies the
// token, decrypts each row, and returns plaintexts.
//
// Deviation from ADR 0007: the Credential.secret field is bytes
// rather than google.protobuf.Struct. Trial scope has no providers
// structuring the payload, so Struct would require a synthetic
// wrapper. The wire shape becomes Struct (or a oneof per provider)
// when provider adapters land. See docs/adr/0007-api-surface.md
// "Update — PRD 0006" for the migration plan.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: coffer/v1/vault.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCredentialsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed per-job capability token (JWT, ed25519). Claims include
	// sub (user_id), credential_ids, aud=coffer-vault, exp.
	GrantToken string `protobuf:"bytes,1,opt,name=grant_token,json=grantToken,proto3" json:"grant_token,omitempty"`
	// Bounded set of credential IDs to fetch. The server rejects
	// requests with more than 8 IDs (ADR 0007).
	CredentialIds []string `protobuf:"bytes,2,rep,name=credential_ids,json=credentialIds,proto3" json:"credential_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialsRequest) Reset() {
	*x = GetCredentialsRequest{}
	mi := &file_coffer_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsRequest) ProtoMessage() {}

func (x *GetCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffer_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_coffer_v1_vault_proto_rawDescGZIP(), []int{0}
}

func (x *GetCredentialsRequest) GetGrantToken() string {
	if x != nil {
		return x.GrantToken
	}
	return ""
}

func (x *GetCredentialsRequest) GetCredentialIds() []string {
	if x != nil {
		return x.CredentialIds
	}
	return nil
}

type GetCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*Credential          `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialsResponse) Reset() {
	*x = GetCredentialsResponse{}
	mi := &file_coffer_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsResponse) ProtoMessage() {}

func (x *GetCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffer_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_coffer_v1_vault_proto_rawDescGZIP(), []int{1}
}

func (x *GetCredentialsResponse) GetCredentials() []*Credential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type Credential struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Label    string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// bytes for trial; will become Struct (or oneof per provider) when
	// provider adapters land. See file header.
	Secret        []byte           `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Metadata      *structpb.Struct `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_coffer_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_coffer_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_coffer_v1_vault_proto_rawDescGZIP(), []int{2}
}

func (x *Credential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Credential) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Credential) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Credential) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *Credential) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_coffer_v1_vault_proto protoreflect.FileDescriptor

const file_coffer_v1_vault_proto_rawDesc = "" +
	"\n" +
	"\x15coffer/v1/vault.proto\x12\tcoffer.v1\x1a\x1cgoogle/protobuf/struct.proto\"_\n" +
	"\x15GetCredentialsRequest\x12\x1f\n" +
	"\vgrant_token\x18\x01 \x01(\tR\n" +
	"grantToken\x12%\n" +
	"\x0ecredential_ids\x18\x02 \x03(\tR\rcredentialIds\"Q\n" +
	"\x16GetCredentialsResponse\x127\n" +
	"\vcredentials\x18\x01 \x03(\v2\x15.coffer.v1.CredentialR\vcredentials\"\x9b\x01\n" +
	"\n" +
	"Credential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\fR\x06secret\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata2^\n" +
	"\x05Vault\x12U\n" +
	"\x0eGetCredentials\x12 .coffer.v1.GetCredentialsRequest\x1a!.coffer.v1.GetCredentialsResponseB@Z>github.com/tumultousRamen/coffer/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_coffer_v1_vault_proto_rawDescOnce sync.Once
	file_coffer_v1_vault_proto_rawDescData []byte
)

func file_coffer_v1_vault_proto_rawDescGZIP() []byte {
	file_coffer_v1_vault_proto_rawDescOnce.Do(func() {
		file_coffer_v1_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coffer_v1_vault_proto_rawDesc), len(file_coffer_v1_vault_proto_rawDesc)))
	})
	return file_coffer_v1_vault_proto_rawDescData
}

var file_coffer_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_coffer_v1_vault_proto_goTypes = []any{
	(*GetCredentialsRequest)(nil),  // 0: coffer.v1.GetCredentialsRequest
	(*GetCredentialsResponse)(nil), // 1: coffer.v1.GetCredentialsResponse
	(*Credential)(nil),             // 2: coffer.v1.Credential
	(*structpb.Struct)(nil),        // 3: google.protobuf.Struct
}
var file_coffer_v1_vault_proto_depIdxs = []int32{
	2, // 0: coffer.v1.GetCredentialsResponse.credentials:type_name -> coffer.v1.Credential
	3, // 1: coffer.v1.Credential.metadata:type_name -> google.protobuf.Struct
	0, // 2: coffer.v1.Vault.GetCredentials:input_type -> coffer.v1.GetCredentialsRequest
	1, // 3: coffer.v1.Vault.GetCredentials:output_type -> coffer.v1.GetCredentialsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coffer_v1_vault_proto_init() }
func file_coffer_v1_vault_proto_init() {
	if File_coffer_v1_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coffer_v1_vault_proto_rawDesc), len(file_coffer_v1_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coffer_v1_vault_proto_goTypes,
		DependencyIndexes: file_coffer_v1_vault_proto_depIdxs,
		MessageInfos:      file_coffer_v1_vault_proto_msgTypes,
	}.Build()
	File_coffer_v1_vault_proto = out.File
	file_coffer_v1_vault_proto_goTypes = nil
	file_coffer_v1_vault_proto_depIdxs = nil
}
